travis:
  secure:
    BINSTAR_TOKEN: 4hZC/dKAvARbIGMq/pqfHlovR1PKf3CZI2peEt0uqCwjYZAaMmh9K2bIbIlHSM06dmOT47ms3h92MzXg1blPu1UEDwg9OVAH771qVgEItn3PHHuzA4NuhBIj4OMEK55Gxcyu/g0wVE/ENMz0ATn2CFKmgRJM7ce7nZihSguaNJcHwOKv/QBjZnburjgE2xRn/9snJC6R/NU9un1+NihAfSZ6s6nNNm4j4Jd84BI5YfINFhmZkf8VJLK/Uzti7JN2f09w2LGqOBFJdeHbN9+wmDyZVqi6fbc6rNE2LVtbJy9KwapWHDb3xI7/ntBKKKt/1uyL8vlVikfefGxWuJUPP1sO+OkNDC6RDKQaMguO4RjRKizEkhid3TKy1pbowboTWt5uBEzUEJkgSW0I2orME+kO1xk3E5nSXiEeuUh45m3C9ur2jQWxrIfkJLcsITArPU/IDiTBHbviXT2LLbpIISEAxKMLfzoFaIrOkPhf6h/9j4SLTqK8Kni0cBuNE1ikKbpvxVKqZhcJGxgQ3H+Gr4Hw4cQfM/AZJ8g8ZFHGX8LBjTHMYRE6I8arrLZcIFnArgP2a5dh17TS06eqXuO7V/f1pmE/++sebKew8rtdz4QjLopMEVNvelzMgpkT27osn3dAaQS0XIsOTLtUgXyG6eVlNW4c09zyOfOFEhoBk8U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
